version: '3.5'

services:

  crdb:
    container_name: crdb
    hostname: crdb
    image: cockroachdb/cockroach-unstable:v20.1.0-beta.1
    command: start --logtostderr --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
  chop-db-init:
    container_name: chop-db-init
    hostname: chop-db-init
    image: timveil/cockroachdb-remote-client:latest
    environment:
      - COCKROACH_HOST=crdb:26257
      - COCKROACH_INSECURE=true
      - DATABASE_NAME=test
    depends_on:
      - crdb